// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protoForBitNet/bitNetToFightingICE.proto
// Protobuf Java Version: 4.33.1

package serverForBitNet;

@com.google.protobuf.Generated
public final class BitNetToFightingICE extends com.google.protobuf.GeneratedFile {
  private BitNetToFightingICE() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "BitNetToFightingICE");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OutputOfBitNetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serverForBitNet.OutputOfBitNet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string OutputOfBitNet = 1;</code>
     * @return The outputOfBitNet.
     */
    java.lang.String getOutputOfBitNet();
    /**
     * <code>string OutputOfBitNet = 1;</code>
     * @return The bytes for outputOfBitNet.
     */
    com.google.protobuf.ByteString
        getOutputOfBitNetBytes();
  }
  /**
   * Protobuf type {@code serverForBitNet.OutputOfBitNet}
   */
  public static final class OutputOfBitNet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serverForBitNet.OutputOfBitNet)
      OutputOfBitNetOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "OutputOfBitNet");
    }
    // Use OutputOfBitNet.newBuilder() to construct.
    private OutputOfBitNet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OutputOfBitNet() {
      outputOfBitNet_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_OutputOfBitNet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_OutputOfBitNet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serverForBitNet.BitNetToFightingICE.OutputOfBitNet.class, serverForBitNet.BitNetToFightingICE.OutputOfBitNet.Builder.class);
    }

    public static final int OUTPUTOFBITNET_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object outputOfBitNet_ = "";
    /**
     * <code>string OutputOfBitNet = 1;</code>
     * @return The outputOfBitNet.
     */
    @java.lang.Override
    public java.lang.String getOutputOfBitNet() {
      java.lang.Object ref = outputOfBitNet_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputOfBitNet_ = s;
        return s;
      }
    }
    /**
     * <code>string OutputOfBitNet = 1;</code>
     * @return The bytes for outputOfBitNet.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOutputOfBitNetBytes() {
      java.lang.Object ref = outputOfBitNet_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputOfBitNet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputOfBitNet_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, outputOfBitNet_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(outputOfBitNet_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, outputOfBitNet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof serverForBitNet.BitNetToFightingICE.OutputOfBitNet)) {
        return super.equals(obj);
      }
      serverForBitNet.BitNetToFightingICE.OutputOfBitNet other = (serverForBitNet.BitNetToFightingICE.OutputOfBitNet) obj;

      if (!getOutputOfBitNet()
          .equals(other.getOutputOfBitNet())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OUTPUTOFBITNET_FIELD_NUMBER;
      hash = (53 * hash) + getOutputOfBitNet().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(serverForBitNet.BitNetToFightingICE.OutputOfBitNet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serverForBitNet.OutputOfBitNet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serverForBitNet.OutputOfBitNet)
        serverForBitNet.BitNetToFightingICE.OutputOfBitNetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_OutputOfBitNet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_OutputOfBitNet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serverForBitNet.BitNetToFightingICE.OutputOfBitNet.class, serverForBitNet.BitNetToFightingICE.OutputOfBitNet.Builder.class);
      }

      // Construct using serverForBitNet.BitNetToFightingICE.OutputOfBitNet.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        outputOfBitNet_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_OutputOfBitNet_descriptor;
      }

      @java.lang.Override
      public serverForBitNet.BitNetToFightingICE.OutputOfBitNet getDefaultInstanceForType() {
        return serverForBitNet.BitNetToFightingICE.OutputOfBitNet.getDefaultInstance();
      }

      @java.lang.Override
      public serverForBitNet.BitNetToFightingICE.OutputOfBitNet build() {
        serverForBitNet.BitNetToFightingICE.OutputOfBitNet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public serverForBitNet.BitNetToFightingICE.OutputOfBitNet buildPartial() {
        serverForBitNet.BitNetToFightingICE.OutputOfBitNet result = new serverForBitNet.BitNetToFightingICE.OutputOfBitNet(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(serverForBitNet.BitNetToFightingICE.OutputOfBitNet result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.outputOfBitNet_ = outputOfBitNet_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serverForBitNet.BitNetToFightingICE.OutputOfBitNet) {
          return mergeFrom((serverForBitNet.BitNetToFightingICE.OutputOfBitNet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serverForBitNet.BitNetToFightingICE.OutputOfBitNet other) {
        if (other == serverForBitNet.BitNetToFightingICE.OutputOfBitNet.getDefaultInstance()) return this;
        if (!other.getOutputOfBitNet().isEmpty()) {
          outputOfBitNet_ = other.outputOfBitNet_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                outputOfBitNet_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object outputOfBitNet_ = "";
      /**
       * <code>string OutputOfBitNet = 1;</code>
       * @return The outputOfBitNet.
       */
      public java.lang.String getOutputOfBitNet() {
        java.lang.Object ref = outputOfBitNet_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          outputOfBitNet_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string OutputOfBitNet = 1;</code>
       * @return The bytes for outputOfBitNet.
       */
      public com.google.protobuf.ByteString
          getOutputOfBitNetBytes() {
        java.lang.Object ref = outputOfBitNet_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          outputOfBitNet_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string OutputOfBitNet = 1;</code>
       * @param value The outputOfBitNet to set.
       * @return This builder for chaining.
       */
      public Builder setOutputOfBitNet(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        outputOfBitNet_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string OutputOfBitNet = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOutputOfBitNet() {
        outputOfBitNet_ = getDefaultInstance().getOutputOfBitNet();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string OutputOfBitNet = 1;</code>
       * @param value The bytes for outputOfBitNet to set.
       * @return This builder for chaining.
       */
      public Builder setOutputOfBitNetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        outputOfBitNet_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serverForBitNet.OutputOfBitNet)
    }

    // @@protoc_insertion_point(class_scope:serverForBitNet.OutputOfBitNet)
    private static final serverForBitNet.BitNetToFightingICE.OutputOfBitNet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new serverForBitNet.BitNetToFightingICE.OutputOfBitNet();
    }

    public static serverForBitNet.BitNetToFightingICE.OutputOfBitNet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OutputOfBitNet>
        PARSER = new com.google.protobuf.AbstractParser<OutputOfBitNet>() {
      @java.lang.Override
      public OutputOfBitNet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OutputOfBitNet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OutputOfBitNet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public serverForBitNet.BitNetToFightingICE.OutputOfBitNet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serverForBitNet.GameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string distance = 1;</code>
     * @return The distance.
     */
    java.lang.String getDistance();
    /**
     * <code>string distance = 1;</code>
     * @return The bytes for distance.
     */
    com.google.protobuf.ByteString
        getDistanceBytes();

    /**
     * <code>string lightPositions = 2;</code>
     * @return The lightPositions.
     */
    java.lang.String getLightPositions();
    /**
     * <code>string lightPositions = 2;</code>
     * @return The bytes for lightPositions.
     */
    com.google.protobuf.ByteString
        getLightPositionsBytes();

    /**
     * <code>string playerState = 3;</code>
     * @return The playerState.
     */
    java.lang.String getPlayerState();
    /**
     * <code>string playerState = 3;</code>
     * @return The bytes for playerState.
     */
    com.google.protobuf.ByteString
        getPlayerStateBytes();

    /**
     * <code>string isbusy = 4;</code>
     * @return The isbusy.
     */
    java.lang.String getIsbusy();
    /**
     * <code>string isbusy = 4;</code>
     * @return The bytes for isbusy.
     */
    com.google.protobuf.ByteString
        getIsbusyBytes();
  }
  /**
   * Protobuf type {@code serverForBitNet.GameState}
   */
  public static final class GameState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serverForBitNet.GameState)
      GameStateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "GameState");
    }
    // Use GameState.newBuilder() to construct.
    private GameState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GameState() {
      distance_ = "";
      lightPositions_ = "";
      playerState_ = "";
      isbusy_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_GameState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_GameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serverForBitNet.BitNetToFightingICE.GameState.class, serverForBitNet.BitNetToFightingICE.GameState.Builder.class);
    }

    public static final int DISTANCE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object distance_ = "";
    /**
     * <code>string distance = 1;</code>
     * @return The distance.
     */
    @java.lang.Override
    public java.lang.String getDistance() {
      java.lang.Object ref = distance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        distance_ = s;
        return s;
      }
    }
    /**
     * <code>string distance = 1;</code>
     * @return The bytes for distance.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDistanceBytes() {
      java.lang.Object ref = distance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIGHTPOSITIONS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lightPositions_ = "";
    /**
     * <code>string lightPositions = 2;</code>
     * @return The lightPositions.
     */
    @java.lang.Override
    public java.lang.String getLightPositions() {
      java.lang.Object ref = lightPositions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lightPositions_ = s;
        return s;
      }
    }
    /**
     * <code>string lightPositions = 2;</code>
     * @return The bytes for lightPositions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLightPositionsBytes() {
      java.lang.Object ref = lightPositions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lightPositions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERSTATE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object playerState_ = "";
    /**
     * <code>string playerState = 3;</code>
     * @return The playerState.
     */
    @java.lang.Override
    public java.lang.String getPlayerState() {
      java.lang.Object ref = playerState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerState_ = s;
        return s;
      }
    }
    /**
     * <code>string playerState = 3;</code>
     * @return The bytes for playerState.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerStateBytes() {
      java.lang.Object ref = playerState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISBUSY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object isbusy_ = "";
    /**
     * <code>string isbusy = 4;</code>
     * @return The isbusy.
     */
    @java.lang.Override
    public java.lang.String getIsbusy() {
      java.lang.Object ref = isbusy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isbusy_ = s;
        return s;
      }
    }
    /**
     * <code>string isbusy = 4;</code>
     * @return The bytes for isbusy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIsbusyBytes() {
      java.lang.Object ref = isbusy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isbusy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(distance_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, distance_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lightPositions_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, lightPositions_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerState_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, playerState_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(isbusy_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, isbusy_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(distance_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, distance_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lightPositions_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, lightPositions_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerState_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, playerState_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(isbusy_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, isbusy_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof serverForBitNet.BitNetToFightingICE.GameState)) {
        return super.equals(obj);
      }
      serverForBitNet.BitNetToFightingICE.GameState other = (serverForBitNet.BitNetToFightingICE.GameState) obj;

      if (!getDistance()
          .equals(other.getDistance())) return false;
      if (!getLightPositions()
          .equals(other.getLightPositions())) return false;
      if (!getPlayerState()
          .equals(other.getPlayerState())) return false;
      if (!getIsbusy()
          .equals(other.getIsbusy())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getDistance().hashCode();
      hash = (37 * hash) + LIGHTPOSITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getLightPositions().hashCode();
      hash = (37 * hash) + PLAYERSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerState().hashCode();
      hash = (37 * hash) + ISBUSY_FIELD_NUMBER;
      hash = (53 * hash) + getIsbusy().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static serverForBitNet.BitNetToFightingICE.GameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static serverForBitNet.BitNetToFightingICE.GameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static serverForBitNet.BitNetToFightingICE.GameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(serverForBitNet.BitNetToFightingICE.GameState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serverForBitNet.GameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serverForBitNet.GameState)
        serverForBitNet.BitNetToFightingICE.GameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_GameState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_GameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serverForBitNet.BitNetToFightingICE.GameState.class, serverForBitNet.BitNetToFightingICE.GameState.Builder.class);
      }

      // Construct using serverForBitNet.BitNetToFightingICE.GameState.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        distance_ = "";
        lightPositions_ = "";
        playerState_ = "";
        isbusy_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serverForBitNet.BitNetToFightingICE.internal_static_serverForBitNet_GameState_descriptor;
      }

      @java.lang.Override
      public serverForBitNet.BitNetToFightingICE.GameState getDefaultInstanceForType() {
        return serverForBitNet.BitNetToFightingICE.GameState.getDefaultInstance();
      }

      @java.lang.Override
      public serverForBitNet.BitNetToFightingICE.GameState build() {
        serverForBitNet.BitNetToFightingICE.GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public serverForBitNet.BitNetToFightingICE.GameState buildPartial() {
        serverForBitNet.BitNetToFightingICE.GameState result = new serverForBitNet.BitNetToFightingICE.GameState(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(serverForBitNet.BitNetToFightingICE.GameState result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.distance_ = distance_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lightPositions_ = lightPositions_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.playerState_ = playerState_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isbusy_ = isbusy_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serverForBitNet.BitNetToFightingICE.GameState) {
          return mergeFrom((serverForBitNet.BitNetToFightingICE.GameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serverForBitNet.BitNetToFightingICE.GameState other) {
        if (other == serverForBitNet.BitNetToFightingICE.GameState.getDefaultInstance()) return this;
        if (!other.getDistance().isEmpty()) {
          distance_ = other.distance_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLightPositions().isEmpty()) {
          lightPositions_ = other.lightPositions_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPlayerState().isEmpty()) {
          playerState_ = other.playerState_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getIsbusy().isEmpty()) {
          isbusy_ = other.isbusy_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                distance_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                lightPositions_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                playerState_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                isbusy_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object distance_ = "";
      /**
       * <code>string distance = 1;</code>
       * @return The distance.
       */
      public java.lang.String getDistance() {
        java.lang.Object ref = distance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          distance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string distance = 1;</code>
       * @return The bytes for distance.
       */
      public com.google.protobuf.ByteString
          getDistanceBytes() {
        java.lang.Object ref = distance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          distance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string distance = 1;</code>
       * @param value The distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistance(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        distance_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string distance = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistance() {
        distance_ = getDefaultInstance().getDistance();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string distance = 1;</code>
       * @param value The bytes for distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        distance_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object lightPositions_ = "";
      /**
       * <code>string lightPositions = 2;</code>
       * @return The lightPositions.
       */
      public java.lang.String getLightPositions() {
        java.lang.Object ref = lightPositions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lightPositions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lightPositions = 2;</code>
       * @return The bytes for lightPositions.
       */
      public com.google.protobuf.ByteString
          getLightPositionsBytes() {
        java.lang.Object ref = lightPositions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lightPositions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lightPositions = 2;</code>
       * @param value The lightPositions to set.
       * @return This builder for chaining.
       */
      public Builder setLightPositions(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lightPositions_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string lightPositions = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLightPositions() {
        lightPositions_ = getDefaultInstance().getLightPositions();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string lightPositions = 2;</code>
       * @param value The bytes for lightPositions to set.
       * @return This builder for chaining.
       */
      public Builder setLightPositionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lightPositions_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object playerState_ = "";
      /**
       * <code>string playerState = 3;</code>
       * @return The playerState.
       */
      public java.lang.String getPlayerState() {
        java.lang.Object ref = playerState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerState_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string playerState = 3;</code>
       * @return The bytes for playerState.
       */
      public com.google.protobuf.ByteString
          getPlayerStateBytes() {
        java.lang.Object ref = playerState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string playerState = 3;</code>
       * @param value The playerState to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerState(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        playerState_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string playerState = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerState() {
        playerState_ = getDefaultInstance().getPlayerState();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string playerState = 3;</code>
       * @param value The bytes for playerState to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        playerState_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object isbusy_ = "";
      /**
       * <code>string isbusy = 4;</code>
       * @return The isbusy.
       */
      public java.lang.String getIsbusy() {
        java.lang.Object ref = isbusy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isbusy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isbusy = 4;</code>
       * @return The bytes for isbusy.
       */
      public com.google.protobuf.ByteString
          getIsbusyBytes() {
        java.lang.Object ref = isbusy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isbusy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isbusy = 4;</code>
       * @param value The isbusy to set.
       * @return This builder for chaining.
       */
      public Builder setIsbusy(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        isbusy_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string isbusy = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsbusy() {
        isbusy_ = getDefaultInstance().getIsbusy();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string isbusy = 4;</code>
       * @param value The bytes for isbusy to set.
       * @return This builder for chaining.
       */
      public Builder setIsbusyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        isbusy_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serverForBitNet.GameState)
    }

    // @@protoc_insertion_point(class_scope:serverForBitNet.GameState)
    private static final serverForBitNet.BitNetToFightingICE.GameState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new serverForBitNet.BitNetToFightingICE.GameState();
    }

    public static serverForBitNet.BitNetToFightingICE.GameState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameState>
        PARSER = new com.google.protobuf.AbstractParser<GameState>() {
      @java.lang.Override
      public GameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GameState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public serverForBitNet.BitNetToFightingICE.GameState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serverForBitNet_OutputOfBitNet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serverForBitNet_OutputOfBitNet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serverForBitNet_GameState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serverForBitNet_GameState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(protoForBitNet/bitNetToFightingICE.pro" +
      "to\022\017serverForBitNet\"(\n\016OutputOfBitNet\022\026\n" +
      "\016OutputOfBitNet\030\001 \001(\t\"Z\n\tGameState\022\020\n\010di" +
      "stance\030\001 \001(\t\022\026\n\016lightPositions\030\002 \001(\t\022\023\n\013" +
      "playerState\030\003 \001(\t\022\016\n\006isbusy\030\004 \001(\t2`\n\021Fig" +
      "htingIceServer\022K\n\nGameStream\022\037.serverFor" +
      "BitNet.OutputOfBitNet\032\032.serverForBitNet." +
      "GameState\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_serverForBitNet_OutputOfBitNet_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_serverForBitNet_OutputOfBitNet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serverForBitNet_OutputOfBitNet_descriptor,
        new java.lang.String[] { "OutputOfBitNet", });
    internal_static_serverForBitNet_GameState_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_serverForBitNet_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serverForBitNet_GameState_descriptor,
        new java.lang.String[] { "Distance", "LightPositions", "PlayerState", "Isbusy", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
